services:

  hapi:
    build: ./hapi-fhir-jpaserver-starter
    container_name: fhir_server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

    # Variáveis opcionais — não configuram o banco,
    # mas o HAPI Starter não quebra se deixarmos.
    environment:
      - HAPI_FHIR_FHIR_VERSION=R4
      - HAPI_FHIR_DATABASE_TYPE=postgresql


  db:
    image: postgres:14-alpine
    container_name: fhir_db
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_USER=hapi_user
      - POSTGRES_PASSWORD=hapi_password
    volumes:
      - fhir-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hapi_user -d hapi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  fhir-db-data:
